### ISSUE TITLE
Última tela de vendas - add botão

### ISSUE THREAD

**Issue by rivanbello** [tahnamao/fael-sales#314]
- [x] Na última tela do checkout criar um botão "Clique para realizar seu vestibular".
- [x] O link deve abrir uma nova aba.
- [x] Abaixo do botão inserir o seguinte texto: "A não conclusão do vestibular não anula o serviço contratado."

**Comment by thayanedeassis** [comment]
aguardando correção da "geração" de links @DAWestphal

**Comment by DAWestphal** [comment]
corrigido com pull #332
