### ISSUE TITLE
Tela de licenças

### ISSUE THREAD

**Issue by rivanbello** [tahnamao/fael-sales#330]
Path - `localhost:3000/cadastrar`

- [x] Resolver o responsivo
- [x] Sempre deixar os 4 planos em todas as resoluções, quando não for possível aplicar o carrossel.
- [x] Botão "Quero minha licença" deve fazer o slide-down para o formulário de cadastro.
- [x] Avaliar a logo se ela não está fixa. Aplicar responsividade.
- [x] Testar tela em geral em diferente resoluções e ajustar.
- [x] Aplicar cores
- [x] Aplicar texto

![image](https://user-images.githubusercontent.com/8796097/105095886-0cfd2900-5a85-11eb-8e85-efefc2da3f4b.png)

**Comment by rivanbello** [comment]
Análise:

- [ ] As cores ainda não estão ok.
- [ ] Responsivo para celular ainda da tela branca.

**Comment by rivanbello** [comment]
https://1drv.ms/u/s!AsTCWdjCbb6DhacHm_o2sVvsoN713Q?e=7OEFvX

**Comment by rivanbello** [comment]
![image](https://user-images.githubusercontent.com/8796097/105526710-86815b00-5cc1-11eb-8126-ae07c8b81b94.png)

**Comment by seralterego** [comment]
> Análise:
> 
> * [x]  As cores ainda não estão ok.
> * [x]  Responsivo para celular ainda da tela branca.
> * [x]  Tem palavras que estão iniciando com letrar minúsculas (títulos).

> Resoluções:
>
> * Cores ajustadas conforme Figma e logo
> * Resposivo resolvido com atualização do plugin carrossel e ajuste no useQuery
> * Palavras corrigidas conforme imagem de modelo.
